name: macOS Tests
on:
  workflow_dispatch:
  push:
    branches: [main, 'release/v*']
  pull_request:
    branches: [main, 'release/v*']

jobs:
  unit-test:
    name: Unit Tests (macOS)
    timeout-minutes: 60
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Run Unit Tests
        uses: ./.github/actions/tests/run-unit-tests

  cli-test:
    name: CLI Tests (macOS)
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Run CLI Tests
        uses: ./.github/actions/tests/run-cli-tests

  e2e-test:
    name: Playwright E2E Tests (macOS)
    timeout-minutes: 90
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Run E2E Tests
        uses: ./.github/actions/tests/run-e2e-tests
        with:
          os: macos

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-macos
          path: playwright-report/
          retention-days: 30

  ssl-test:
    name: SSL Tests (macOS)
    timeout-minutes: 60
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Setup Feature Dependencies
        uses: ./.github/actions/ssl/macos/setup-feature-specific-deps

      - name: Setup CA Certificates
        uses: ./.github/actions/ssl/macos/setup-ca-certs

      - name: Run Basic SSL CLI Tests
        uses: ./.github/actions/ssl/macos/run-basic-ssl-cli-tests

      - name: Run Custom CA Certs CLI Tests
        uses: ./.github/actions/ssl/macos/run-custom-ca-certs-cli-tests

      - name: Run Custom CA Certs E2E Tests
        uses: ./.github/actions/ssl/macos/run-ssl-e2e-tests